### ISSUE TITLE
'png.h' file not foundsyntax error near unexpected token `|'

### ISSUE THREAD

**Issue by rcolsm** [twg/png2escpos#2]
When I,

$ ./png2escpos <7.png> | lpr -P EPSON_TM_T82_S_A

-bash: syntax error near unexpected token `|'

How do I fix it?

**Comment by Abaxial** [comment]
I haven't yet used this myself, but a quick question, are you typing it exactly as:

`$ ./png2escpos <7.png> | lpr -P EPSON_TM_T82_S_A`

If so, try:

`$ ./png2escpos 7.png | lpr -P EPSON_TM_T82_S_A`

I believe the <> in the documentation is to indicate the variability of the file.png within the brackets.  

Let me know if this helps your problem.

**Comment by rcolsm** [comment]
Abaxial,

Thank you very much, that fixed the problem. I am new to this kind of thing, thanks for your help.
