### ISSUE TITLE
Unable to compile - "undefined reference to" - changed Makefile and it worked

### ISSUE THREAD

**Issue by jpfranca1977** [twg/png2escpos#3]
Hi! 

I was getting a lot of "undefined reference to..." errors when trying to compile:

```
api@v11465:~/png2escpos$ make
gcc -std=c99 -Wall -L/usr/lib/x86_64-linux-gnu -lpng -O3 png2escpos.c -o png2escpos
/tmp/ccs30k0E.o: In function `read_png_file':
png2escpos.c:(.text+0x21): undefined reference to `png_create_read_struct'
png2escpos.c:(.text+0x3a): undefined reference to `png_create_info_struct'
png2escpos.c:(.text+0x5f): undefined reference to `png_set_longjmp_fn'
png2escpos.c:(.text+0x81): undefined reference to `png_init_io'
png2escpos.c:(.text+0x91): undefined reference to `png_read_info'
png2escpos.c:(.text+0x9c): undefined reference to `png_get_image_width'
png2escpos.c:(.text+0xad): undefined reference to `png_get_image_height'
png2escpos.c:(.text+0xbe): undefined reference to `png_get_color_type'
png2escpos.c:(.text+0xcf): undefined reference to `png_get_bit_depth'
png2escpos.c:(.text+0x109): undefined reference to `png_get_valid'
png2escpos.c:(.text+0x143): undefined reference to `png_read_update_info'
png2escpos.c:(.text+0x186): undefined reference to `png_get_rowbytes'
png2escpos.c:(.text+0x1b2): undefined reference to `png_read_image'
png2escpos.c:(.text+0x1d6): undefined reference to `png_set_gray_to_rgb'
png2escpos.c:(.text+0x1f0): undefined reference to `png_set_filler'
png2escpos.c:(.text+0x206): undefined reference to `png_set_tRNS_to_alpha'
png2escpos.c:(.text+0x215): undefined reference to `png_set_expand_gray_1_2_4_to_8'
png2escpos.c:(.text+0x224): undefined reference to `png_set_palette_to_rgb'
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'png2escpos' failed
make: *** [png2escpos] Error 1
```

Looking for a solution, I found this comment [here](https://stackoverflow.com/questions/22426574/gcc-undefined-reference-to) : "Please also note that **libraries need to be specified on the command line after the files needing them**".

With that in mind, I changed the Makefile, putting the library ( ${INC} ) **after** the source ( ${SRC} ):

```
${OUTPUT}: ${SRC}
        ${COMPILER} ${FLAGS} -O3 ${SRC} ${INC} -o ${OUTPUT}
```

and was able to compile. Not sure if it's something specific to my gcc version. 

BTW, thanks for the good work, png2escpos was exactly what I needed.

**Comment by mike42** [comment]
@jpfranca1977 - I can replicate this in an Ubuntu Precise environment with GCC 4.6.3, but not on a Debian Stretch environment with GCC 6.3.0, so it's a GCC version difference, and I've applied your fix downstream in [my fork](https://github.com/mike42/png2escpos) to improve compatbility.

I have had a pull request sitting here for two years, so I'm fairly sure that this project is a zombie. [png2pos](https://github.com/petrkutalek/png2pos) is a good alternative which can dither correctly, but it is also officially unmaintained.

**Comment by mike42** [comment]
The fix for this has now been merged.

Thanks for reporting!
